### PR TITLE
ipython 8.1.1 merged from conda-forge

### PR DESCRIPTION
**Pull request by dholth**
Version change: bump version number from 7.31.1 to 8.1.1
Changelog: https://ipython.readthedocs.io/en/stable/whatsnew/version8.html
Bug Tracker: new open issues https://github.com/ipython/ipython/issues
Upstream license:  License file:  https://github.com/ipython/ipython/blob/master/LICENSE
Upstream setup.py:  https://github.com/ipython/ipython/blob/8.1.1/setup.py
Upstream setup.cfg: https://github.com/ipython/ipython/blob/8.1.1/setup.cfg
Upstream pyproject.toml: https://github.com/ipython/ipython/blob/8.1.1/pyproject.toml

### CODE REVIEW

**Comment by dholth** [comment]
https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#dependencies-changes-downstream-packaging

- minimum supported traitlets version is now 5+
- we now require stack_data
- minimal Python is now 3.8
- nose is not a testing requirement anymore
- pytest replaces nose
- iptest/iptest3 cli entrypoints do not exists anymore.
- minimum officially support numpy version has been bumped, but this should not have much effect on packaging.

**Comment by skupr-anaconda** [comment]
We need to add `stack_data` and its dependencies: `executing`, `asttokens`, `pure_eval `https://github.com/AnacondaRecipes/stack_data-feedstock/pull/1

**Comment by skupr-anaconda** [comment]
I  added pinning for setuptools and remove pytest pinning

**Comment by skupr-anaconda** [comment]
I've just added `stack_data`, `executing`, `asttokens`, and  `pure_eval`

**Comment by skupr-anaconda** [comment]
Unsatisfiable dependencies for platform linux-ppc64le. I think some package hasn't python 3.10 support

**Pull request merged**
